image: python:3.12

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "course_recommender"
  MYSQL_ROOT_PASSWORD: "1234!@#E"

stages:
  - Environment_Setup
  - Client_DB_Connection
  - Client_Function_Test
  - Admin_DB_Connection
  - Admin_Function_Test
  - Admin_API_Test
  - Merge

Test_Evnironment:
  stage: Environment_Setup
  script: 
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

Client Connection:
  stage: Client_DB_Connection
  script:
    - echo "Testing Client DB Connection..."
    - pytest ./test/test_client_dbconnection.py -v
  needs: ["Test_Evnironment"]

Client Function:
  stage: Client_Function_Test
  script:
    - echo "Testing Client Functions..."
    - pytest ./test/test_client_function.py -v
  needs: ["Client Connection"]

Admin Connection:
  stage: Admin_DB_Connection
  script:
    - echo "Testing Admin DB Connection..."
    - pytest ./test/test_admin_dbconnection.py -v
  needs: ["Test_Evnironment"]

Admin Function:
  stage: Admin_Function_Test
  script:
    - echo "Testing Admin Functions..."
    - pytest ./test/test_admin_function.py -v
  needs: ["Admin Connection"]

Admin API:
  stage: Admin_API_Test
  script:
    - echo "Testing Admin APIs... but no test cases now..."
  needs: ["Admin Function"]

Merge:
  stage: Merge
  script:
    - echo "Deploying project..."
  needs: ["Admin API", "Client Function"]
