image: python:3.12

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install pytest
  - pip install fastapi uvicorn
  - pip install mysql-connector-python

test:
  stage: test
  script:
    - pytest -v