image: python:3.12

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "course_recommender"
  MYSQL_ROOT_PASSWORD: "1234!@#E"

stages:
  - Environment_Setup
  - DB_Connection
  - Functions_Test
  - Merge

Test_Environment:
  stage: Environment_Setup
  script: 
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python
  artifacts:
    paths: [venv/]

Client_Connection:
  stage: DB_Connection
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Client DB Connection..."
    - pytest ./test/test_client_dbconnection.py -v
  needs: ["Test_Environment"]

Admin_Connection:
  stage: DB_Connection
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Admin DB Connection..."
    - pytest ./test/test_admin_dbconnection.py -v
  needs: ["Test_Environment"]

Client_Function:
  stage: Functions_Test
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Client Functions..."
    - pytest ./test/test_client_function.py -v
  needs: ["Client_Connection"]

Admin_Function:
  stage: Functions_Test
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Admin Functions..."
    - pytest ./test/test_admin_function.py -v
  needs: ["Admin_Connection"]

Merge:
  stage: Merge
  script:
    - echo "Deploying project..."
  needs: ["Admin_Function", "Client_Function"]
