image: python:3.12

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "course_recommender"
  MYSQL_ROOT_PASSWORD: "1234!@#E"

  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - Environment_Setup
  - DB_Connection
  - Functions_Test
  - Build
  - Push

Test_Environment:
  stage: Environment_Setup
  script: 
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python
  artifacts:
    paths: [venv/]

Client_Connection:
  stage: DB_Connection
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Client DB Connection..."
    - pytest ./test/test_client_dbconnection.py -v
  needs: ["Test_Environment"]

Admin_Connection:
  stage: DB_Connection
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Admin DB Connection..."
    - pytest ./test/test_admin_dbconnection.py -v
  needs: ["Test_Environment"]

Client_Function:
  stage: Functions_Test
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Client Functions..."
    - pytest ./test/test_client_function.py -v
  needs: ["Client_Connection"]

Admin_Function:
  stage: Functions_Test
  script:
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

    - echo "Testing Admin Functions..."
    - pytest ./test/test_admin_function.py -v
  needs: ["Admin_Connection"]

Merge:
  stage: Merge
  script:
    - echo "Deploying project..."
  needs: ["Admin_Function", "Client_Function"]

build_image:
  stage: Build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
  needs: ["Merge"]

push_image:
  stage: Push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  needs: ["build_image"]