image: python:3.12

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: $course_recommender
  MYSQL_ROOT_PASSWORD: $1234!@#E

stages:
  - Environment Setup
  - Client DB Connection
  - Client Function Test
  - Admin DB Connection
  - Admin Function Test
  - Admin API Test
  - Merge

Test Evnironment:
  stage: Environment Setup
  script: 
    - echo "Setting up Python environment..."
    - pip install --upgrade pip
    - pip install pytest
    - pip install fastapi uvicorn
    - pip install mysql-connector-python

Client Connection:
  stage: Client DB Connection
  script:
    - echo "Testing Client DB Connection..."
    - pytest .\test\test_client_dbconnection.py -v

Client Function:
  stage: Client Function Test
  script:
    - echo "Testing Client Functions..."
    - pytest .\test\test_client_function.py -v
  needs: ["Client DB Connection"]

Admin Connection:
  stage: Admin DB Connection
  script:
    - echo "Testing Admin DB Connection..."
    - pytest .\test\test_admin_dbconnection.py -v

Admin Function:
  stage: Admin Function Test
  script:
    - echo "Testing Admin Functions..."
    - pytest .\test\test_admin_function.py -v
  needs: ["Admin DB Connection"]

Admin API:
  stage: Admin API Test
  script:
    - echo "Testing Admin APIs... but no test cases now..."
  needs: ["Admin Function Tests"]

Merge:
  stage: Merge
  script:
    - echo "Deploying project..."
  needs: ["Client Function Test", "Admin API Test"]
